### ISSUE TITLE
Register / Registering with an already used email gives no error message

### ISSUE THREAD

**Issue by paquinem** [inf6150-doublej/backend#23]
1. Register using an email (aaaa@gmail.com)
2. Register using that same email (aaaa@gmail.com)

Result:
User stays on register page and has no error displayed

Expected:
An error stipulating the email is already used.

![image](https://user-images.githubusercontent.com/22059607/58386346-7be26000-7fcc-11e9-8ddc-ccaea320b748.png)

**Comment by sgadoury** [comment]
J'ai pas géré les erreurs spécifiques.  J'ai mis un message général
