### ISSUE TITLE
Loading the home page returns an error

### ISSUE THREAD

**Issue by paquinem** [inf6150-doublej/backend#25]
1. backend - flask run
2. frontend - npm start
3. wait for localhost:3000 to load

Result: Backend logs show an error (see picture)

![image](https://user-images.githubusercontent.com/22059607/58386654-d2ea3400-7fd0-11e9-927a-36a64b9e03e6.png)

**Comment by judubjazz** [comment]
should be fixed by branc bugfix-julien
