### ISSUE TITLE
Attempting to log in returns errors

### ISSUE THREAD

**Issue by paquinem** [inf6150-doublej/backend#26]
Way 1:
Register a new user
Attempt to log in

Way 2:
Register a new user
Reboot PC/Services/Servers etc.
Attempt to log in

Errors with SQLite: 
![image](https://user-images.githubusercontent.com/22059607/58386719-b39fd680-7fd1-11e9-9130-48304e1116a9.png)

**Comment by judubjazz** [comment]
was unable to repeat the issue, probably fixed by an unknown branch
