### ISSUE TITLE
Register / Registering an account doesn't save to the DB

### ISSUE THREAD

**Issue by paquinem** [inf6150-doublej/backend#28]
I registered 2 different accounts:

eg191144@ens.uqam.ca
and
paquin.emilie.5@courrier.uqam.ca

None of them show in the database.
I cannot log in with either of them.

NOTE:
I was able to log in with eg191144@ens.uqam.ca but as soon as i closed my session, the account disappeared. It still did not save to the DB.

**Comment by judubjazz** [comment]
should be fixed by branc bugfix-julien
