### ISSUE TITLE
home/ LOGIN button no longer works

### ISSUE THREAD

**Issue by paquinem** [inf6150-doublej/backend#32]
The LOGIN button now does nothing:

Backend log:
127.0.0.1 - - [28/May/2019 20:01:32] "OPTIONS /getuser HTTP/1.1" 200 -
127.0.0.1 - - [28/May/2019 20:01:32] "POST /getuser HTTP/1.1" 200 -

on localhost:3000 -> Clicking Login seems to only refresh the page.

**Comment by sgadoury** [comment]
unable to reproduce

**Comment by paquinem** [comment]
From a fresh install:
drop tables
create tables
insert

flask run

npm start

Log in -> It won't work.
You need to register to get the login functionality to start working again

**Comment by sgadoury** [comment]
Found it and fix it.  the cookie existed but was empty
